// <auto-generated />
using System;
using GestaoPiscina.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoPiscina.Server.Migrations
{
    [DbContext(typeof(GestaoPiscinaContext))]
    [Migration("20260912062446_AddChecklistItensOrdemDeServico")]
    partial class AddChecklistItensOrdemDeServico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GestaoPiscina.Server.Models.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiasDeVisita")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.DosagemProduto", b =>
                {
                    b.Property<int>("IDDosagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDOS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDProduto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("IDDosagem");

                    b.HasIndex("IDOS");

                    b.HasIndex("IDProduto");

                    b.ToTable("DosagensProdutos");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Equipamento", b =>
                {
                    b.Property<int>("IDEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("IDCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaCalibragem")
                        .HasColumnType("TEXT");

                    b.HasKey("IDEquipamento");

                    b.HasIndex("IDCliente");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.EstoqueCliente", b =>
                {
                    b.Property<int>("IDEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDProduto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("QuantidadeMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("IDEstoque");

                    b.HasIndex("IDCliente");

                    b.HasIndex("IDProduto");

                    b.ToTable("EstoqueClientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Gestor", b =>
                {
                    b.Property<int>("IDGestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IDGestor");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.GestorCliente", b =>
                {
                    b.Property<int>("IDGestor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDGestor", "IDCliente");

                    b.HasIndex("IDCliente");

                    b.ToTable("GestorClientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("IDMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IDDosagem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuantidadeContada")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IDMovimentacao");

                    b.HasIndex("IDDosagem");

                    b.HasIndex("IDProduto");

                    b.HasIndex("IDCliente", "IDProduto");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.OrdemDeServico", b =>
                {
                    b.Property<int>("IDOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Alcalinidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Aprovador")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChecklistConcluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChecklistItens")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CloroLivre")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DurezaCalcica")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotosAntes")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotosDepois")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotosOcorrencias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraTermino")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDPiscina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RelatorioGerado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("pH")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("IDOS");

                    b.HasIndex("Aprovador");

                    b.HasIndex("IDPiscina");

                    b.HasIndex("IDUsuario");

                    b.ToTable("OrdensDeServico");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Perfil", b =>
                {
                    b.Property<int>("IDPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PodeConfigurarSistema")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarClientes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarEquipamentos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarOrdensServico")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarPiscinas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarProdutos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarUsuarios")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeVisualizarRelatorios")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDPerfil");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Piscina", b =>
                {
                    b.Property<int>("IDPiscina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aquecida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coberta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("IDCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecorrenciaDataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecorrenciaDataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecorrenciaDiasSemana")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecorrenciaFrequencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecorrenciaIntervalo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecorrenciaOcorrencias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecorrenciaTermino")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeLitros")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("IDPiscina");

                    b.HasIndex("IDCliente");

                    b.ToTable("Piscinas");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Produto", b =>
                {
                    b.Property<int>("IDProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Concentracao")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("IDProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("IDPerfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("TEXT");

                    b.HasKey("IDUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IDPerfil");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.DosagemProduto", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.OrdemDeServico", "OrdemDeServico")
                        .WithMany("Dosagens")
                        .HasForeignKey("IDOS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemDeServico");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Equipamento", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("Equipamentos")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.EstoqueCliente", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("Estoques")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.GestorCliente", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("GestorClientes")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Gestor", "Gestor")
                        .WithMany("GestorClientes")
                        .HasForeignKey("IDGestor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.DosagemProduto", "Dosagem")
                        .WithMany()
                        .HasForeignKey("IDDosagem")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestaoPiscina.Server.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Dosagem");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.OrdemDeServico", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Usuario", "AprovadorUsuario")
                        .WithMany()
                        .HasForeignKey("Aprovador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestaoPiscina.Server.Models.Piscina", "Piscina")
                        .WithMany("OrdensDeServico")
                        .HasForeignKey("IDPiscina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadorUsuario");

                    b.Navigation("Piscina");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Piscina", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("Piscinas")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Usuario", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IDPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Cliente", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Estoques");

                    b.Navigation("GestorClientes");

                    b.Navigation("Piscinas");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Gestor", b =>
                {
                    b.Navigation("GestorClientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.OrdemDeServico", b =>
                {
                    b.Navigation("Dosagens");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Piscina", b =>
                {
                    b.Navigation("OrdensDeServico");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Produto", b =>
                {
                    b.Navigation("Estoques");
                });
#pragma warning restore 612, 618
        }
    }
}
