// <auto-generated />
using System;
using GestaoPiscina.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoPiscina.Server.Migrations
{
    [DbContext(typeof(GestaoPiscinaContext))]
    [Migration("20260919072855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoPiscina.Server.Models.ChecklistItem", b =>
                {
                    b.Property<int>("IDChecklistItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistItem"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TiposClienteObrigatorio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiposPiscinaObrigatorio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDChecklistItem");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("ChecklistItens");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCliente"));

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("DiasDeVisita")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.DosagemProduto", b =>
                {
                    b.Property<int>("IDDosagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDosagem"));

                    b.Property<int>("IDOS")
                        .HasColumnType("int");

                    b.Property<int>("IDProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IDDosagem");

                    b.HasIndex("IDOS");

                    b.HasIndex("IDProduto");

                    b.ToTable("DosagensProdutos");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Equipamento", b =>
                {
                    b.Property<int>("IDEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEquipamento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaCalibragem")
                        .HasColumnType("datetime2");

                    b.HasKey("IDEquipamento");

                    b.HasIndex("IDCliente");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.EstoqueCliente", b =>
                {
                    b.Property<int>("IDEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEstoque"));

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IDProduto")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuantidadeMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IDEstoque");

                    b.HasIndex("IDCliente");

                    b.HasIndex("IDProduto");

                    b.ToTable("EstoqueClientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Gestor", b =>
                {
                    b.Property<int>("IDGestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGestor"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDGestor");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.GestorCliente", b =>
                {
                    b.Property<int>("IDGestor")
                        .HasColumnType("int");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.HasKey("IDGestor", "IDCliente");

                    b.HasIndex("IDCliente");

                    b.ToTable("GestorClientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("IDMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMovimentacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IDDosagem")
                        .HasColumnType("int");

                    b.Property<int>("IDProduto")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("QuantidadeContada")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDMovimentacao");

                    b.HasIndex("IDDosagem");

                    b.HasIndex("IDProduto");

                    b.HasIndex("IDCliente", "IDProduto");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.OrdemDeServico", b =>
                {
                    b.Property<int>("IDOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOS"));

                    b.Property<decimal>("Alcalinidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("AlcalinidadeDepois")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int?>("Aprovador")
                        .HasColumnType("int");

                    b.Property<bool>("ChecklistConcluido")
                        .HasColumnType("bit");

                    b.Property<string>("ChecklistItens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CloroLivre")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("CloroLivreDepois")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime?>("DataAprovacaoOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReprovacaoOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DurezaCalcica")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("DurezaCalcicaDepois")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("FotoHodometro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotosDepois")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotosOcorrencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraTermino")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDPiscina")
                        .HasColumnType("int");

                    b.Property<int?>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InicioPercurso")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LatitudeInicio")
                        .HasColumnType("float");

                    b.Property<double?>("LongitudeInicio")
                        .HasColumnType("float");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OcorrenciaAprovada")
                        .HasColumnType("bit");

                    b.Property<bool>("OcorrenciaReprovada")
                        .HasColumnType("bit");

                    b.Property<bool>("RelatorioGerado")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("pH")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("pHDepois")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IDOS");

                    b.HasIndex("Aprovador");

                    b.HasIndex("IDPiscina");

                    b.HasIndex("IDUsuario");

                    b.ToTable("OrdensDeServico");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Perfil", b =>
                {
                    b.Property<int>("IDPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPerfil"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PodeConfigurarSistema")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarClientes")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarEquipamentos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarEstoque")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarOrdensServico")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarPiscinas")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarProdutos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeGerenciarUsuarios")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeVisualizarRelatorios")
                        .HasColumnType("bit");

                    b.HasKey("IDPerfil");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Piscina", b =>
                {
                    b.Property<int>("IDPiscina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPiscina"));

                    b.Property<bool>("Aquecida")
                        .HasColumnType("bit");

                    b.Property<string>("Coberta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RecorrenciaDataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RecorrenciaDataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecorrenciaDiasSemana")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecorrenciaFrequencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RecorrenciaIntervalo")
                        .HasColumnType("int");

                    b.Property<int?>("RecorrenciaOcorrencias")
                        .HasColumnType("int");

                    b.Property<string>("RecorrenciaTermino")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IDPiscina");

                    b.HasIndex("IDCliente");

                    b.ToTable("Piscinas");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Produto", b =>
                {
                    b.Property<int>("IDProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProduto"));

                    b.Property<decimal?>("Concentracao")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IDProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.PushSubscriptionRegistro", b =>
                {
                    b.Property<int>("IDPushSubscriptionRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPushSubscriptionRegistro"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDPushSubscriptionRegistro");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("IDUsuario");

                    b.ToTable("PushSubscriptionRegistros");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.RotaVisita", b =>
                {
                    b.Property<int>("IDRotaVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRotaVisita"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("IDRotaVisita");

                    b.HasIndex("IDCliente");

                    b.HasIndex("IDUsuario", "Data", "IDCliente")
                        .IsUnique();

                    b.ToTable("RotaVisitas");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IDPerfil")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("IDUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IDPerfil");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.DosagemProduto", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.OrdemDeServico", "OrdemDeServico")
                        .WithMany("Dosagens")
                        .HasForeignKey("IDOS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemDeServico");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Equipamento", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("Equipamentos")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.EstoqueCliente", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("Estoques")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.GestorCliente", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("GestorClientes")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Gestor", "Gestor")
                        .WithMany("GestorClientes")
                        .HasForeignKey("IDGestor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.DosagemProduto", "Dosagem")
                        .WithMany()
                        .HasForeignKey("IDDosagem");

                    b.HasOne("GestaoPiscina.Server.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IDProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Dosagem");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.OrdemDeServico", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Usuario", "AprovadorUsuario")
                        .WithMany()
                        .HasForeignKey("Aprovador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestaoPiscina.Server.Models.Piscina", "Piscina")
                        .WithMany("OrdensDeServico")
                        .HasForeignKey("IDPiscina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AprovadorUsuario");

                    b.Navigation("Piscina");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Piscina", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany("Piscinas")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.PushSubscriptionRegistro", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.RotaVisita", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoPiscina.Server.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Usuario", b =>
                {
                    b.HasOne("GestaoPiscina.Server.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IDPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Cliente", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Estoques");

                    b.Navigation("GestorClientes");

                    b.Navigation("Piscinas");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Gestor", b =>
                {
                    b.Navigation("GestorClientes");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.OrdemDeServico", b =>
                {
                    b.Navigation("Dosagens");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Piscina", b =>
                {
                    b.Navigation("OrdensDeServico");
                });

            modelBuilder.Entity("GestaoPiscina.Server.Models.Produto", b =>
                {
                    b.Navigation("Estoques");
                });
#pragma warning restore 612, 618
        }
    }
}
